/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as OpsAdminRouteImport } from './routes/ops/admin'
import { Route as OpsDeskRouteImport } from './routes/ops/desk'
import { Route as OpsEngRouteImport } from './routes/ops/eng'
import { Route as OpsMyRouteImport } from './routes/ops/my'
import { Route as OpsQaRouteImport } from './routes/ops/qa'
import { Route as OpsReleasesRouteImport } from './routes/ops/releases'
import { Route as OpsTriageRouteImport } from './routes/ops/triage'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalIdRouteImport } from './routes/portal/$id'
import { Route as PortalNewRouteImport } from './routes/portal/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OpsDeskIndexRouteImport } from './routes/ops/desk/index'
import { Route as OpsDeskIdRouteImport } from './routes/ops/desk/$id'
import { Route as OpsEngIndexRouteImport } from './routes/ops/eng/index'
import { Route as OpsEngIdRouteImport } from './routes/ops/eng/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsAdminRoute = OpsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => OpsRoute,
} as any)
const OpsDeskRoute = OpsDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => OpsRoute,
} as any)
const OpsEngRoute = OpsEngRouteImport.update({
  id: '/eng',
  path: '/eng',
  getParentRoute: () => OpsRoute,
} as any)
const OpsMyRoute = OpsMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => OpsRoute,
} as any)
const OpsQaRoute = OpsQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => OpsRoute,
} as any)
const OpsReleasesRoute = OpsReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => OpsRoute,
} as any)
const OpsTriageRoute = OpsTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => OpsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalIdRoute = PortalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNewRoute = PortalNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PortalRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsDeskIndexRoute = OpsDeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsDeskRoute,
} as any)
const OpsDeskIdRoute = OpsDeskIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpsDeskRoute,
} as any)
const OpsEngIndexRoute = OpsEngIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsEngRoute,
} as any)
const OpsEngIdRoute = OpsEngIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpsEngRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/ops/admin': typeof OpsAdminRoute
  '/ops/desk': typeof OpsDeskRouteWithChildren
  '/ops/eng': typeof OpsEngRouteWithChildren
  '/ops/my': typeof OpsMyRoute
  '/ops/qa': typeof OpsQaRoute
  '/ops/releases': typeof OpsReleasesRoute
  '/ops/triage': typeof OpsTriageRoute
  '/portal/$id': typeof PortalIdRoute
  '/portal/new': typeof PortalNewRoute
  '/ops/': typeof OpsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ops/desk/$id': typeof OpsDeskIdRoute
  '/ops/eng/$id': typeof OpsEngIdRoute
  '/ops/desk/': typeof OpsDeskIndexRoute
  '/ops/eng/': typeof OpsEngIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops/admin': typeof OpsAdminRoute
  '/ops/my': typeof OpsMyRoute
  '/ops/qa': typeof OpsQaRoute
  '/ops/releases': typeof OpsReleasesRoute
  '/ops/triage': typeof OpsTriageRoute
  '/portal/$id': typeof PortalIdRoute
  '/portal/new': typeof PortalNewRoute
  '/ops': typeof OpsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ops/desk/$id': typeof OpsDeskIdRoute
  '/ops/eng/$id': typeof OpsEngIdRoute
  '/ops/desk': typeof OpsDeskIndexRoute
  '/ops/eng': typeof OpsEngIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/ops/admin': typeof OpsAdminRoute
  '/ops/desk': typeof OpsDeskRouteWithChildren
  '/ops/eng': typeof OpsEngRouteWithChildren
  '/ops/my': typeof OpsMyRoute
  '/ops/qa': typeof OpsQaRoute
  '/ops/releases': typeof OpsReleasesRoute
  '/ops/triage': typeof OpsTriageRoute
  '/portal/$id': typeof PortalIdRoute
  '/portal/new': typeof PortalNewRoute
  '/ops/': typeof OpsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/ops/desk/$id': typeof OpsDeskIdRoute
  '/ops/eng/$id': typeof OpsEngIdRoute
  '/ops/desk/': typeof OpsDeskIndexRoute
  '/ops/eng/': typeof OpsEngIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ops'
    | '/portal'
    | '/ops/admin'
    | '/ops/desk'
    | '/ops/eng'
    | '/ops/my'
    | '/ops/qa'
    | '/ops/releases'
    | '/ops/triage'
    | '/portal/$id'
    | '/portal/new'
    | '/ops/'
    | '/portal/'
    | '/api/auth/$'
    | '/ops/desk/$id'
    | '/ops/eng/$id'
    | '/ops/desk/'
    | '/ops/eng/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ops/admin'
    | '/ops/my'
    | '/ops/qa'
    | '/ops/releases'
    | '/ops/triage'
    | '/portal/$id'
    | '/portal/new'
    | '/ops'
    | '/portal'
    | '/api/auth/$'
    | '/ops/desk/$id'
    | '/ops/eng/$id'
    | '/ops/desk'
    | '/ops/eng'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/ops'
    | '/portal'
    | '/ops/admin'
    | '/ops/desk'
    | '/ops/eng'
    | '/ops/my'
    | '/ops/qa'
    | '/ops/releases'
    | '/ops/triage'
    | '/portal/$id'
    | '/portal/new'
    | '/ops/'
    | '/portal/'
    | '/api/auth/$'
    | '/ops/desk/$id'
    | '/ops/eng/$id'
    | '/ops/desk/'
    | '/ops/eng/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/admin': {
      id: '/ops/admin'
      path: '/admin'
      fullPath: '/ops/admin'
      preLoaderRoute: typeof OpsAdminRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/desk': {
      id: '/ops/desk'
      path: '/desk'
      fullPath: '/ops/desk'
      preLoaderRoute: typeof OpsDeskRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/eng': {
      id: '/ops/eng'
      path: '/eng'
      fullPath: '/ops/eng'
      preLoaderRoute: typeof OpsEngRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/my': {
      id: '/ops/my'
      path: '/my'
      fullPath: '/ops/my'
      preLoaderRoute: typeof OpsMyRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/qa': {
      id: '/ops/qa'
      path: '/qa'
      fullPath: '/ops/qa'
      preLoaderRoute: typeof OpsQaRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/releases': {
      id: '/ops/releases'
      path: '/releases'
      fullPath: '/ops/releases'
      preLoaderRoute: typeof OpsReleasesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/triage': {
      id: '/ops/triage'
      path: '/triage'
      fullPath: '/ops/triage'
      preLoaderRoute: typeof OpsTriageRouteImport
      parentRoute: typeof OpsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/$id': {
      id: '/portal/$id'
      path: '/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof PortalIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/new': {
      id: '/portal/new'
      path: '/new'
      fullPath: '/portal/new'
      preLoaderRoute: typeof PortalNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/desk/': {
      id: '/ops/desk/'
      path: '/'
      fullPath: '/ops/desk/'
      preLoaderRoute: typeof OpsDeskIndexRouteImport
      parentRoute: typeof OpsDeskRoute
    }
    '/ops/desk/$id': {
      id: '/ops/desk/$id'
      path: '/$id'
      fullPath: '/ops/desk/$id'
      preLoaderRoute: typeof OpsDeskIdRouteImport
      parentRoute: typeof OpsDeskRoute
    }
    '/ops/eng/': {
      id: '/ops/eng/'
      path: '/'
      fullPath: '/ops/eng/'
      preLoaderRoute: typeof OpsEngIndexRouteImport
      parentRoute: typeof OpsEngRoute
    }
    '/ops/eng/$id': {
      id: '/ops/eng/$id'
      path: '/$id'
      fullPath: '/ops/eng/$id'
      preLoaderRoute: typeof OpsEngIdRouteImport
      parentRoute: typeof OpsEngRoute
    }
  }
}

interface OpsDeskRouteChildren {
  OpsDeskIdRoute: typeof OpsDeskIdRoute
  OpsDeskIndexRoute: typeof OpsDeskIndexRoute
}

const OpsDeskRouteChildren: OpsDeskRouteChildren = {
  OpsDeskIdRoute: OpsDeskIdRoute,
  OpsDeskIndexRoute: OpsDeskIndexRoute,
}

const OpsDeskRouteWithChildren =
  OpsDeskRoute._addFileChildren(OpsDeskRouteChildren)

interface OpsEngRouteChildren {
  OpsEngIdRoute: typeof OpsEngIdRoute
  OpsEngIndexRoute: typeof OpsEngIndexRoute
}

const OpsEngRouteChildren: OpsEngRouteChildren = {
  OpsEngIdRoute: OpsEngIdRoute,
  OpsEngIndexRoute: OpsEngIndexRoute,
}

const OpsEngRouteWithChildren =
  OpsEngRoute._addFileChildren(OpsEngRouteChildren)

interface OpsRouteChildren {
  OpsAdminRoute: typeof OpsAdminRoute
  OpsDeskRoute: typeof OpsDeskRouteWithChildren
  OpsEngRoute: typeof OpsEngRouteWithChildren
  OpsMyRoute: typeof OpsMyRoute
  OpsQaRoute: typeof OpsQaRoute
  OpsReleasesRoute: typeof OpsReleasesRoute
  OpsTriageRoute: typeof OpsTriageRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsAdminRoute: OpsAdminRoute,
  OpsDeskRoute: OpsDeskRouteWithChildren,
  OpsEngRoute: OpsEngRouteWithChildren,
  OpsMyRoute: OpsMyRoute,
  OpsQaRoute: OpsQaRoute,
  OpsReleasesRoute: OpsReleasesRoute,
  OpsTriageRoute: OpsTriageRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface PortalRouteChildren {
  PortalIdRoute: typeof PortalIdRoute
  PortalNewRoute: typeof PortalNewRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIdRoute: PortalIdRoute,
  PortalNewRoute: PortalNewRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
